### ISSUE TITLE
Keyframe rule ignored due to bad selector.

### ISSUE THREAD

**Issue by bejucoo** [imgix/luminous#586] opened 2021-12-28 16:50 UTC
Hello,

I'm getting a `Keyframe rule ignored due to bad selector.` warning in Firefox 95.0.1. Is it something to worry? I tried in Chrome 96.0.4664.110  and it doesn't appear.

**Comment by sherwinski** [comment] 2021-12-29 17:01
Hi @bejucoo, could you please provide a reproducible demo that would throw this warning? That would help us look into it.

**Comment by luqven** [comment] 2022-09-30 17:18
Hey there @bejucoo,

Since there hasn't been any movement recently on this issue I'm going to go ahead and close it. If you still have an issue/questions please comment and I'll be happy to re-open it.

**Closed by luqven** 2022-09-30 17:18 UTC
