### ISSUE TITLE
The image file's height is over when the image is big size

### ISSUE THREAD

**Issue by Haduki029** [imgix/luminous#565] opened 2021-08-13 08:36 UTC
**Before you submit:**

- [x] Please search through the existing issues (both open AND closed) to see if your question has already been discussed. Github issue search can be used for this: https://github.com/imgix/luminous/issues?utf8=%E2%9C%93&q=is%3Aissue

**Question**
The image file's height is over the window's height when the image is big size in google chrome and edge browsers.
Do you have any plans to deal with this?

**Comment by frederickfogerty** [comment] 2021-08-13 11:21
Hi @Haduki029 👋 thank you for the issue.

It's hard to understand this specific problem without a screenshot or a way to reproduce this issue. Do you think you could provide either of these? Thanks!

**Comment by Ronamo** [comment] 2021-08-13 17:52
> Hi @Haduki029 👋 thank you for the issue.
> 
> It's hard to understand this specific problem without a screenshot or a way to reproduce this issue. Do you think you could provide either of these? Thanks!

https://honeycomb.liftoff.shop/vertical-poster-print

Clicking on the product image on this page reproduces the issue.

This issue is present in the current (as of 13-8-21) versions of Chrome and Edge (appears to be Webkit/Blink related) under both Mac OS and Windows, but not present in Firefox or Safari under Mac OS.

**Comment by frederickfogerty** [comment] 2021-08-16 11:52
Thanks for the repro, I can see the issue now.

The right solution here is probably to modernise the way the positioning happens in the Lightbox to use Flexbox. Unfortunately I don't think we will have time to prioritise this work internally for a while, but I will add this to the backlog to see what happens.

Alternatively, a quick fix for your situation would be to set `display` to `block` for `.lum-lightbox-image-wrapper`. As code that would look like this:

```css
.lum-lightbox-image-wrapper {
  display: block !important; 
}
```

I am hesitant to blindly update this library with this change since a) it will probably break in IE, and b) I would need to do some other cross-browser testing. 

Let me know how this goes for you. Also, if you would like to submit a PR reworking this positioning to use Flexbox, or updating this CSS and doing some testing in evergreen browsers, I would gladly accept it. Thanks!

**Comment by Haduki029** [comment] 2021-08-25 02:40
Hi, @frederickfogerty 
Thank you for fast responsive and your alternatively fix idea.
I will try it and let you know about result.

**Comment by Karynvo** [comment] 2021-09-03 06:13
It worked on Chrome for me @frederickfogerty. Thanks! Depending on how you want it to behave on mobile though, when you click on the image, the image will go to full size. I just removed this from the CSS instead of adding display:block;

```
.lum-lightbox-inner img{max-width:none;max-height:none}
```

Not fully sure of the repercussions on other browsers, but it did the job for me

**Comment by sherwinski** [comment] 2022-06-21 22:19
Closing this as there appears to be an adequate answer provided.

**Closed by sherwinski** 2022-06-21 22:19 UTC
