### ISSUE TITLE
Can't get prev/next arrows to work

### ISSUE THREAD

**Issue by NicholasJohn16** [imgix/luminous#74] opened 2018-09-29 07:27 UTC
I wanted to see with the arrow navigation looked like in Luminous, so I download a zip of the repo real quick, edited the index.html file and changed the js to the following:

```new LuminousGallery(
document.querySelectorAll('.gallery-demo'), 
{
  arrowNavigation: true
}, 
{
  caption: function (trigger) {
    return trigger.querySelector('img').getAttribute('alt');
  }
});
```

But the arrow navigation doesn't seem to work. No new icons appear and the arrow keys don't do anything. Am I missing something? Thank you for your help and great library.

**Comment by frederickfogerty** [comment] 2018-10-03 00:41
Hey there @NicholasJohn16, sorry to hear that you've had issue with Luminous! This is on my list of issues to look at for the next two weeks. I'll keep this issue updated with my progress.

**Comment by hellorich** [comment] 2018-10-11 10:47
Hi @frederickfogerty - I've had what I think may be similar issues with the Gallery functionality as @NicholasJohn16  - I'm not entirely sure its working as intended, either locally in my project (standard Luminous lightbox seems fine) nor in codepens I've based on the Lightbox example, modified using Gallery code in the readme.

Here's one of my pens: https://codepen.io/anon/pen/RegwWp

It seems the first image loads in a lightbox, but any others simply load the linked image.

**Comment by SiamKreative** [comment] 2018-10-12 09:48
Same issue here

**Comment by AlexisWalravens** [comment] 2018-11-11 14:09
Same issue here, was there any progress on this ?

**Comment by frederickfogerty** [comment] 2018-11-17 19:18
Hi all. This was a regression from a previous release and is fixed in the PR #121. If you would like to checkout that PR and test that it fixes the problem, that would be much appreciated. Otherwise, sit tight and a fix should be released soon!

**Closed** 2018-12-02 15:49 UTC
Labels: Priority: High, Status: Discussion, Type: Bug
